### ISSUE TITLE
create script to extract weather stations for each fine area of interest

### ISSUE THREAD

**Issue by rchang0501** [WAT-ai/wildfire#26]
## Definitions
* Fine area of interest: each square
* Coarse area of interest: the big rectangle (Kelowna)

![Image](https://github.com/WAT-ai/wildfire/assets/46568041/19f036da-b8b7-4a4e-9c2f-d5dd345d048e)

## Task

- [x] determine how to divide Kelowna into fine areas of interest (how to split the rectangle into smaller squares/rectangles)
- [x] Given a file of weather stations in Kelowna, extract the stations for each fine area of interest into their own file

```
Kelowna -> fine area 1, fine area 2, fine area 3
```

#### File of weather stations in the coarse area of interest (kelowna): 
`kelowna_stations.csv`
| Station Name    | Longitude | Latitude |
| -------- | ------- | ------- |
| Station 1  | 100  | 100   |
| Station 2  | 110  | 100   |
| Station 3  | 120  | 100   |
| Station 4  | 200  | 100   |
| Station 5  | 210  | 100   |
| Station 6  | 220  | 100   |
| Station 7  | 300  | 100   |
| Station 8  | 310  | 100   |
| Station 9  | 320  | 100   |

#### Extract the stations into their fine area of interests:
`fine_area_1_stations.csv`
| Station Name    | Longitude | Latitude |
| -------- | ------- | ------- |
| Station 1  | 100  | 100   |
| Station 2  | 110  | 100   |
| Station 3  | 120  | 100   |

`fine_area_2_stations.csv`
| Station Name    | Longitude | Latitude |
| -------- | ------- | ------- |
| Station 4  | 200  | 100   |
| Station 5  | 210  | 100   |
| Station 6  | 220  | 100   |

`fine_area_3_stations.csv`
| Station Name    | Longitude | Latitude |
| -------- | ------- | ------- |
| Station 7  | 300  | 100   |
| Station 8  | 310  | 100   |
| Station 9  | 320  | 100   |

## Implementation details
* Go to `data/weather-stations/kelowna`. 
* The directory is already set up with a `kelowna_stations.csv`
* Your task should be extracting the data into the `fine_area_#_stations.csv` files
* The number of fine areas is based on how you decide to split up kelowna

**Comment by Ari1029** [comment]
Some notes on potential approach/findings:
- the Kelowna region is a rectangle with differing height and width. A straightforward approach 
   would be to create small regions of same aspect ratio as overall area
- this could involve specifying the number of latitude (horizontal) and longitude (vertical) splits 
   required in order to generate several rows for the fine area station
- upon some calculations, the separation in latitude for 12 splits horizontally would be 0.125 and 
   the separation in longitude for 12 splits vertically would be 0.178. 
- Using the following calculator: https://www.omnicalculator.com/other/latitude-longitude- 
  distance, this corresponds to an 8.34km height and and 11.702km width
- defined a function to determine the number of fine areas with 0 stations in order to determine 
   optimal split. can use number of fine regions as hyper parameter for XGBoost model training

**Comment by paigekobz** [comment]
created PR for this!
